### ISSUE TITLE
Parsing breaks when sample types are used

### ISSUE THREAD

**Issue by dcnadler** [BPSB/Synergy-File-Reader#1]
version: 1.2.2

In the Synergy software (Gen5), under the Plate Layout configuration within the Protocol, sample types can be assigned to each well (e.g. Blank, Assay Control, Samples, etc.).

If any well has a sample type set, the `SynergyFile` cannot parse the output txt file data.
```
ValueError: File does not appear to have a valid or implemented format.
```

There would need new parsers added, for example when sample types are set in the plate layout there is a Layout section of the txt file:
```
Layout
	1	2	3	4	5	6	7	8	9	10	11	12
A	SPL2	SPL10	SPL18	SPL26	SPL34	SPL42	SPL50	SPL58	SPL66	SPL74	SPL82	SPL90	Well ID
B	SPL3	SPL11	SPL19	SPL27	SPL35	SPL43	SPL51	SPL59	SPL67	SPL75	SPL83	SPL91	Well ID
C	SPL4	SPL12	SPL20	SPL28	SPL36	SPL44	SPL52	SPL60	SPL68	SPL76	SPL84	SPL92	Well ID
D	SPL5	SPL13	SPL21	SPL29	SPL37	SPL45	SPL53	SPL61	SPL69	SPL77	SPL85	SPL93	Well ID
E	SPL6	SPL14	SPL22	SPL30	SPL38	SPL46	SPL54	SPL62	SPL70	SPL78	SPL86	SPL94	Well ID
F	SPL7	SPL15	SPL23	SPL31	SPL39	SPL47	SPL55	SPL63	SPL71	SPL79	SPL87	SPL95	Well ID
G	SPL8	SPL16	SPL24	SPL32	SPL40	SPL48	SPL56	SPL64	SPL72	SPL80	SPL88	SPL96	Well ID
H	SPL9	SPL17	SPL25	SPL33	SPL41	SPL49	SPL57	SPL65	SPL73	SPL81	SPL89	SPL97	Well ID
```

And the Results section has an extra column with the WELL ID:
```
Results

Well ID	Well	Read 1:600	Count	Mean	Std Dev	CV (%)
SPL2	A1	0.112	1	0.112	?????	?????
SPL3	B1	0.104	1	0.104	?????	?????
SPL4	C1	0.096	1	0.096	?????	?????
SPL5	D1	0.106	1	0.106	?????	?????
SPL6	E1	0.099	1	0.099	?????	?????
```

Would be great if that handling was added, but still an amazing tool without that feature. Thanks!

**Comment by Wrzlprmft** [comment]
I created some test files myself and implemented the necessary changes to read them. However, these are still different in format from what you describe (I didn’t use the right format options), so your use case is untested until I can create the respective files.

Please try the current version from Github. You should be able to install it with something like:
```
pip3 install git+git://github.com/BPSB/Synergy-File-Reader
```

**Comment by dcnadler** [comment]
@Wrzlprmft Thanks so much for looking into this!

I've attached some example export files below. For all I selected Content=automatic, and under content tab selected everything. I have two versions of each, one with row-wise tables, one with column-wise tables.

Most of the exports are from example experiment files (.xpt) that come with the Gen5 software. I also see they have some here as well: https://www.biotek.com/products/software-robotics-software/gen5-microplate-reader-and-imager-software/software/

The last two files (custom-kinetic) are examples with my actual data and is the simplest plate layout - each well is a unique standard sample, spl1 to spl96 (no replication).

I'll try the github version of your package on my data in the next week or so. Thanks again!

[Direct Oligo Quantification Blank Plate with data col-wise.txt](https://github.com/BPSB/Synergy-File-Reader/files/7551681/Direct.Oligo.Quantification.Blank.Plate.with.data.col-wise.txt)
[Direct Oligo Quantification Blank Plate with data row-wise.txt](https://github.com/BPSB/Synergy-File-Reader/files/7551683/Direct.Oligo.Quantification.Blank.Plate.with.data.row-wise.txt)
[Propidium Iodide with Data col-wise.txt](https://github.com/BPSB/Synergy-File-Reader/files/7551684/Propidium.Iodide.with.Data.col-wise.txt)
[Propidium Iodide with Data row-wise.txt](https://github.com/BPSB/Synergy-File-Reader/files/7551685/Propidium.Iodide.with.Data.row-wise.txt)
[Tryptophan Quantitation with Data col-wise.txt](https://github.com/BPSB/Synergy-File-Reader/files/7551686/Tryptophan.Quantitation.with.Data.col-wise.txt)
[Tryptophan Quantitation with Data row-wise.txt](https://github.com/BPSB/Synergy-File-Reader/files/7551687/Tryptophan.Quantitation.with.Data.row-wise.txt)
[Yeast_Growth_Kinetic_600nm_col-wise.txt](https://github.com/BPSB/Synergy-File-Reader/files/7551688/Yeast_Growth_Kinetic_600nm_col-wise.txt)
[Yeast_Growth_Kinetic_600nm_row-wise.txt](https://github.com/BPSB/Synergy-File-Reader/files/7551689/Yeast_Growth_Kinetic_600nm_row-wise.txt)
[custom-kinetic_col-wise.txt](https://github.com/BPSB/Synergy-File-Reader/files/7551690/custom-kinetic_col-wise.txt)
[custom-kinetic_row-wise.txt](https://github.com/BPSB/Synergy-File-Reader/files/7551692/custom-kinetic_row-wise.txt)

**Comment by Wrzlprmft** [comment]
The current GitHub version successfully parses all your test files now. I haven’t thoroughly checked the content though but see no reason why that should fail.

**Comment by dcnadler** [comment]
Thanks @Wrzlprmft!! The current version worked on my system to parse all test files I posted.

I did find one file that it had issues with. This is likely a more rare case, but a user for some reason had a few samples out of order which caused the ordering in the file to not start at row A.
Specifically it started with G8:
```
Results

Well ID	Well	Read 1:600	Count	Mean	Std Dev	CV (%)
SPL1	G8	0.083	1	0.083	?????	?????
SPL2	A1	0.112	1	0.112	?????	?????
SPL3	B1	0.104	1	0.104	?????	?????
.
.
.
```
This raises an error here: https://github.com/BPSB/Synergy-File-Reader/blob/master/synergy_file_reader/_synergy_file_reader.py#L86

Is it possible to remove that assertion? It looks like you removed the same assertion for columns in your last commit https://github.com/BPSB/Synergy-File-Reader/commit/56445a64a3f3d777043eb8eb8c99f6dc3b80f406

Here are example files I made where ordering is not logically from A1 and also raises the same assertion error:
[mixed_sample_order_col-wise.txt](https://github.com/BPSB/Synergy-File-Reader/files/7637955/mixed_sample_order_col-wise.txt)
[mixed_sample_order_row-wise.txt](https://github.com/BPSB/Synergy-File-Reader/files/7637956/mixed_sample_order_row-wise.txt)
1

**Comment by Wrzlprmft** [comment]
Indeed; done.

**Comment by dcnadler** [comment]
Great!

I've noticed a couple more things looking deeper at the results from the test files I posted above.

---

It seems that when a sample type is ever used on more than one well, the software will automatically add four values to the output for each sample_id: 'Count', 'Mean', 'Std Dev', 'CV (%)'.

In the `custom-kinetic_col-wise.txt` file above, e.g., every well has a unique sample id, so this is not  in the output. But most of the other files have some replication of sample_ids across multiple wells so have those values show up.  There doesn't seem to be a way to prevent this output in the software (at least in all the settings I could find).

There are a few issues this causes:

First, there's no way to distinguish these from actual channels, which is why right now they end up as channels in the `SynergyPlate`s and the values get assigned to the first well of the replicates that appears in the file.

In addition, if multiple values are output (e.g. `Direct Oligo Quantification Blank Plate with data col-wise.txt` has 'Blank Plate:260', 'Pathlength', '260', etc.), the 'Mean', 'Std Dev', 'CV (%)' are only calculated for the last value that shows up. In Direct Oligo file, it's calculated for 'Concentration' (the last value listed in the file before 'Count').

Lastly, this can cause an erroneous RepeatingData error if multiple read types are done in one run. E.g. I'll get RepeatingData error for index  ('A', 1, 'Count') when it starts to parse the second result. This will create a second plate even though it was only one plate.

One suggestion might be to detect 'Count', 'Mean', 'Std Dev', 'CV (%)', throw out 'Mean', 'Std Dev', 'CV (%)' and store 'Count' as metadata on the sample_id info. Or just throw out all 4, since the underlying data is in the parsed data.

---

File `Direct Oligo Quantification Blank Plate with data col-wise.txt`, for example, has some value names with brackets that don't have a channel, e.g. 977 [Test] or 900 [Ref].

Maybe the extracted "channel" can be checked against channels found so far? https://github.com/BPSB/Synergy-File-Reader/blob/master/synergy_file_reader/_synergy_file_reader.py#L272

That would prevent 977 [Test] and 900 [Ref] from being put in plate.results, since I think it's more appropriate that they end up in plate.channels.

**Comment by Wrzlprmft** [comment]
> I've noticed a couple more things looking deeper at the results from the test files I posted above.

Thank you for your feedback. The issues should be addressed now.

> Or just throw out all 4, since the underlying data is in the parsed data.

Since I don’t think anybody needs these, I went for this easiest solution.

> File `Direct Oligo Quantification Blank Plate with data col-wise.txt`, for example, has some value names with brackets that don't have a channel, e.g. 977 [Test] or 900 [Ref].
> 
> Maybe the extracted "channel" can be checked against channels found so far? https://github.com/BPSB/Synergy-File-Reader/blob/master/synergy_file_reader/_synergy_file_reader.py#L272
> 
> That would prevent 977 [Test] and 900 [Ref] from being put in plate.results, since I think it's more appropriate that they end up in plate.channels.

Done as suggested.

**Comment by dcnadler** [comment]
@Wrzlprmft: thank you so much! Works perfectly!

Could you push this to a new release? Much appreciated!

**Comment by Wrzlprmft** [comment]
> Could you push this to a new release? Much appreciated!

Sure. I just wanted to wait until every problem is solved.
